# Gitleaks configuration file

[extend]
useDefault = true

# Правило для Telegram Bot Token
[[rules]]
id = "telegram-bot-token"
description = "Telegram Bot Token"
regex = '''[0-9]{8,10}:[a-zA-Z0-9_-]{35}'''
tags = ["telegram", "bot", "token"]

# Правило для Telegram Bot Token у змінних
[[rules]]
id = "telegram-bot-token-env"
description = "Telegram Bot Token in Environment Variable"
regex = '''(?i)telegram.*token.*[=:]\s*['"]*[0-9]{8,10}:[a-zA-Z0-9_-]{35}['"]*'''
tags = ["telegram", "bot", "token"]
